apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wr1fyk11s-python
  janus-idp.io/tekton: wr1fyk11s-python
  backstage.io/kubernetes-id: wr1fyk11s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wr1fyk11s-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
